config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/monitor/health', to: 'monitor#health'
  # mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  resources :file_upload, only: [:new, :create]


  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    cas_sessions: "users/cas_sessions",
  }

  devise_scope :user do
    authenticated :user do
      # Rails 4 users must specify the 'as' option to give it a unique name
      root :to => "home#home", :as => :authenticated_root
    end

    unauthenticated :user do
      root :to => "devise/cas_sessions#new"
    end
  end

  resources :reports, :only => [:index]

  resources :diagrams do
    member do
      get 'download'
    end
  end

  resources :users do
    collection do
      get :export_users_awaiting_approval
      get :export_all
    end
  end

  resources :institutions

  resources :user_logs, only: [] do
    collection do
      get :export
    end
  end

  get 'home' => 'home#home'
  get 'home/news'
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :users, :dependent => :delete_all
  has_many :diagrams, :dependent => :delete_all

  def users_awaiting_approval
    users.where(:approved => false)
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, :only => [:show, :edit, :update, :destroy]
  before_action :set_institutions, :only => [:index]

  before_action :user_is_super_admin, :except => :create

  # skip_before_action :authenticate_user!, :only => :create
  # skip_before_action :user_signed_in?, :only => :create
  # skip_before_action :current_user, :only => :create
  # skip_before_action :user_session, :only => :create

  #Enforces access right checks for individuals resources
  after_action :verify_authorized

  # Enforces access right checks for collections
  after_action :verify_policy_scoped, :only => :index


  def index
    authorize Institution
    respond_with(@institutions)
  end

  def show
    respond_with(@institution)
  end

  def new
    @institution = Institution.new
    authorize @institution
    respond_with(@institution)
  end

  def edit
  end

  def create
    @institution = Institution.new(institution_params)
    authorize @institution

    @institution.save!

    render json: @institution
  end

  def update
    @institution.update(institution_params)
    flash[:notice] = "#{controller_name.classify} successfully updated."
    respond_with(@institution)
  end

  def destroy
    @institution.destroy
    respond_with(@institution)
  end

  private
    def set_institution
      @institution = Institution.find(params[:id])
      authorize @institution
    end

    def set_institutions
      @institutions = policy_scope(Institution)
    end

    def institution_params
      params.require(:institution).permit(:name)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.haml
= form_for @institution do |f|
  - if @institution.errors.any?
    #error_explanation
      %h2= "#{pluralize(@institution.errors.count, "error")} prohibited this institution from being saved:"
      %ul
        - @institution.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/institutions/edit.html.haml
%h2 Editing institution

= render 'form'

= link_to 'Show', @institution
\|
= link_to 'Back', institutions_path

app/views/institutions/index.html.haml
#header
  %p
    You are:
    %a{ href: user_path(current_user) }
      = current_user.name
  .slicknav-container
    .slicknav
    %ul#menu{ style: "display:none;" }
      %li= link_to 'Home', root_path
      - if policy(User).index?
        %li= link_to 'Users', users_path
      - if policy(Diagram).create?
        %li
          Diagrams
          %ul
            %li= link_to 'List', diagrams_path
            %li= link_to 'Create', new_diagram_path
      - else
        %li= link_to 'Diagrams', diagrams_path
      - if current_user.super_admin
        %li= link_to 'Institutions', institutions_path
      %li= link_to 'Sign out', destroy_user_session_path, method: :delete

  %h1#site_title
    = link_to "Ribbon Tool", root_path
%h2 Listing institutions

%table.datatable.responsive.no-wrap
  %thead
    %tr
      %th Name
      %th
      %th
      %th
  %tbody
    - @institutions.each do |institution|
      %tr
        %td= institution.name
        %td= link_to 'Show', institution
        %td= link_to 'Edit', edit_institution_path(institution)
        %td= link_to 'Destroy', institution, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Institution', new_institution_path

app/views/institutions/new.html.haml
#header
  %p
    You are:
    %a{ href: user_path(current_user) }
      = current_user.name
  .slicknav-container
    .slicknav
    %ul#menu{ style: "display:none;" }
      %li= link_to 'Home', root_path
      - if policy(User).index?
        %li= link_to 'Users', users_path
      - if policy(Diagram).create?
        %li
          Diagrams
          %ul
            %li= link_to 'List', diagrams_path
            %li= link_to 'Create', new_diagram_path
      - else
        %li= link_to 'Diagrams', diagrams_path
      - if current_user.super_admin
        %li= link_to 'Institutions', institutions_path
      %li= link_to 'Sign out', destroy_user_session_path, method: :delete

  %h1#site_title
    = link_to "Ribbon Tool", root_path
%h2 New institution

= render 'form'

= link_to 'Back', institutions_path

app/views/institutions/show.html.haml
%p
  %b Name:
  = @institution.name

%table.datatable.responsive.no-wrap
  %thead
    %tr
      %th Name
      %th Email
      %th Roles
  %tbody
    - @institution.users.each do |user|
      %tr
        %td= link_to user.name, user
        %td= user.email
        %td
          - if user.role_list.empty?
            No Roles Assigned
          - else
            - user.role_list.each do |role|
              = role
              %br

= link_to 'Edit', edit_institution_path(@institution)
\|
= link_to 'Back', institutions_path