config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/monitor/health', to: 'monitor#health'
  # mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  resources :file_upload, only: [:new, :create]


  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    cas_sessions: "users/cas_sessions",
  }

  devise_scope :user do
    authenticated :user do
      # Rails 4 users must specify the 'as' option to give it a unique name
      root :to => "home#home", :as => :authenticated_root
    end

    unauthenticated :user do
      root :to => "devise/cas_sessions#new"
    end
  end

  resources :reports, :only => [:index]

  resources :diagrams do
    member do
      get 'download'
    end
  end

  resources :users do
    collection do
      get :export_users_awaiting_approval
      get :export_all
    end
  end

  resources :institutions

  resources :user_logs, only: [] do
    collection do
      get :export
    end
  end

  get 'home' => 'home#home'
  get 'home/news'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :skip_password_validation

  # devise :database_authenticatable,
  devise :registerable,
         :cas_authenticatable,
         :recoverable,
         :rememberable,
         :trackable
        #  :validatable#,
        #  :confirmable

  royce_roles %w[
    institution-admin

    user-view
    user-update
    user-set-roles
    user-approve
    user-destroy

    diagram-create
    diagram-update
    diagram-destroy
    diagram-download
  ]


  belongs_to :institution

  validates :email, uniqueness: { message: "%{value} has already been taken." }
  validates :username, uniqueness: { message: "%{value} has already been taken." }
  validates :uid_number, uniqueness: { message: "%{value} has already been taken." }
  validates_presence_of :institution
  validates_presence_of :name, :title, :department

  has_many :user_diagrams, :dependent => :delete_all
  has_many :diagrams, :through => :user_diagrams
  has_many :user_logs, dependent: :destroy

  has_many :authored_diagrams, :class_name => "Diagram", :foreign_key => :creator_id

  after_create :send_admin_mail

  def send_admin_mail
    AdminMailer.new_user_waiting_for_approval(self).deliver
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def role_dependencies
    {
        "user-update" => "user-view",
        "user-destroy" => "user-view",
        "user-approve" => "user-update",
        "user-set-roles" => "user-update",
        "diagram-update" => "diagram-create",
        "diagram-destroy" => "diagram-create"
    }
  end

  def dependent_roles
    {
        "user-view" => %w(user-update user-destroy user-approve user-set-roles),
        "user-update" => %w(user-approve user-set-roles),
        "diagram-create" => %w(diagram-update diagram-destroy)
    }
  end

  def cas_extra_attributes=(extra_attributes)
    # [["username", "divyansh"], ["LIMIT", 1]]
    # {"u_id"=>"119400043",
    # "sn"=>"Shrivastava",
    # "uid"=>"divyansh",
    # "givenName"=>"Divyansh",
    # "cn"=>"Divyansh Shrivastava",
    # "email"=>"divyansh@umd.edu",
    # "employeeNumber"=>"119400043"}
    extra_attributes.each do |name, value|
      case name.to_sym
      when :fullname
        self.fullname = valuesel
      when :email
        self.email = value
      end
    end
  end
end

app/controllers/users/cas_sessions_controller.rb
class Users::CasSessionsController < Devise::SessionsController
  def new
    RackCAS.config.service = cas_service_url
    head 401

    if !resource.nil? and resource.errors.any? 
      redirect_to new_user_registration_path, alert: "Invalid credentials"
    end
  end

  def service
    self.resource = warden.authenticate!(auth_options)

    if !resource.nil? and resource.errors.any? 
      redirect_to after_sign_in_path_for(warden.authenticate!(:scope => resource_name, on_failure: "#{new_user_registration_path}")), allow_other_host: true
    else
      redirect_to new_user_registration_path
    end
  end

  def create
    super # Call Devise's original logic
    if resource and resource.errors.any? 
      redirect_to new_user_registration_path, alert: "Invalid credentials"
    end
  end 

  def auth_options
    { scope: resource_name, recall: "#{new_user_registration_path}" }
  end

  def unregistered; end

  def destroy
    # if :cas_create_user is false a CAS session might be open but not signed_in
    # in such case we destroy the session here
    if signed_in?(resource_name)
      sign_out(resource_name)
      session.delete('cas')
    else
      reset_session
    end

    redirect_to(cas_logout_url, allow_other_host: true)
  end

  private

  def cas_login_url
    RackCAS::Server.new(RackCAS.config.server_url).login_url(cas_service_url).to_s
  end
  helper_method :cas_login_url

  def request_url
    return @request_url if @request_url

    @request_url = request.protocol.dup
    @request_url << request.host
    @request_url << ":#{request.port}" unless request.port == 80
    @request_url
  end

  def cas_destination_url
    return unless ::Devise.cas_logout_url_param == 'destination'

    if !::Devise.cas_destination_url.blank?
      Devise.cas_destination_url
    else
      url = request_url.dup
      url << after_sign_out_path_for(resource_name)
    end
  end

  def cas_follow_url
    return unless ::Devise.cas_logout_url_param == 'follow'

    if !::Devise.cas_follow_url.blank?
      Devise.cas_follow_url
    else
      url = request_url.dup
      url << after_sign_out_path_for(resource_name)
    end
  end

  def cas_service_url
    # binding.pry
    ::Devise.cas_service_url(request_url.dup, devise_mapping)
  end

  def cas_logout_url
    server = RackCAS::Server.new(RackCAS.config.server_url)
    destination_url = cas_destination_url
    follow_url = cas_follow_url
    service_url = cas_service_url

    if destination_url
      server.logout_url(destination: destination_url, gateway: 'true').to_s
    elsif follow_url
      server.logout_url(url: follow_url, service: service_url).to_s
    else
      server.logout_url(service: service_url).to_s
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  #def create
  #  super
  #end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
    if @user.approved && @user.confirmed?
      AdminMailer.approved_notify(@user).deliver
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # skip_before_action :authenticate_user!
  before_action :sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:title, :department])
  end

  def sign_up_params
   params.require(:user).permit(:title, :department, :email, :password, :password_confirmation, :username, :name, :institution_id, :approved, :why_give_access, :how_did_you_learn_about, user_diagrams: [])
  end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'csv'

  before_action :set_user, :only => [:show, :edit, :update, :destroy]
  before_action :set_users, :only => [:index]

  #Enforces access right checks for individuals resources
  after_action :verify_authorized

  # Enforces access right checks for collections
  after_action :verify_policy_scoped, :only => :index

  def index
    authorize User
    if params[:approved] == "false"
      @users = @users.where(:approved => false)
    end

    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new

    authorize @user

    respond_with(@user)
  end

  def edit
  end

  #Not called. Replaced by
  def create
    @user = User.new(user_params)

    authorize @user
    @user.save

    respond_with(@user)
  end

  def update
    was_approved = @user.approved
    if @user.update_attributes(user_params)
      if policy(current_user).set_roles?
        set_roles
      end

      if policy(current_user).approve?
        if !was_approved && @user.approved# && @user.confirmed?
          AdminMailer.approved_notify(@user).deliver
        end
      end

      share

      flash[:notice] = "#{controller_name.classify} successfully updated."
    end

    respond_with(@user)
  end

  def export_users_awaiting_approval
    authorize User

    output_csv = CSV.generate({:force_quotes => true}) do |csv|
      csv << %w(name email title department signup_date)
      User.where(:approved => false).where(:institution_id => current_user.institution_id).each do |user|
        csv << [user.name, user.email, user.title, user.department, user.created_at.strftime("%F")]
      end
    end

    send_data(output_csv, :type => 'text/csv', :disposition => :attachment, :filename => "ribbon_users_awaiting_approval_as_of_#{DateTime.now.strftime("%F")}.csv")

  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  def export_all
    authorize User  # Pundit authorization

    users = policy_scope(User)

    csv_data = CSV.generate(headers: true) do |csv|
      csv << [
        "ID", "Institution ID", "Super Admin", "Name", "Email", "Title", "Department", "Username",
        "UID Number", "Approved", "Sign In Count", "Last Sign In At",
        "Created At", "Updated At"
      ]

      users.each do |user|
        csv << [
          user.id,
          user.institution_id,
          user.super_admin,
          user.name,
          user.email,
          user.title,
          user.department,
          user.username,
          user.uid_number,
          user.approved,
          user.sign_in_count,
          user.last_sign_in_at&.in_time_zone("Eastern Time (US & Canada)")&.strftime("%Y-%m-%d %H:%M"),
          user.created_at&.in_time_zone("Eastern Time (US & Canada)")&.strftime("%Y-%m-%d %H:%M"),
          user.updated_at&.in_time_zone("Eastern Time (US & Canada)")&.strftime("%Y-%m-%d %H:%M")
        ]
      end
    end

    send_data csv_data, filename: "all_users_#{Time.now.strftime('%Y%m%d')}.csv"
  end

  private
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    def set_users
      @users = policy_scope(User)
    end

    def set_roles
      @user.role_list.each do |role|
        @user.remove_role role
      end

      if params[:roles]
        puts params[:roles]
        params[:roles].split(",").each do |role|
          if policy(:role).set_role?(role)
            @user.add_role role
          end
        end
      end
    end

    def share
      @user.diagrams = []
      if params[:user_diagrams]
        params[:user_diagrams].each do |diagrams_id|
          if @user.institution.diagrams.map(&:id).include?(diagrams_id.to_i)
            UserDiagram.new(:diagram_id => diagrams_id.to_i, :user_id => @user.id).save!
          end
        end
      end
    end

    def user_params
      if current_user.super_admin
        params.require(:user).permit(:institution_id, :name, :email, :title, :department, :approved, :roles)
      else
        params.require(:user).permit(:name, :email, :title, :department, :approved, :roles)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .indent
    - if current_user.super_admin
      .field
        = f.label :institution_id, "Institution"
        = f.select(:institution_id,  options_for_select(Institution.all.map{|u| [u.name, u.id]}, :selected => @user.institution.id))

    .field
      = f.label :name
      = f.text_field :name

    .field
      = f.label :email
      = f.text_field :email

    .field
      = f.label :title
      = f.text_field :title

    .field
      = f.label :department
      = f.text_field :department

    .field
      = f.label :username, "UMD Directory ID"
      = f.text_field :username

    .field
      = f.label :uid_number, "UMD Directory ID Number"
      = f.text_field :uid_number

    .field
      = f.label :why_give_access, "Why to give access?"
      = f.text_area :why_give_access, rows: 5, class: 'new_user_text_fields'

    .field
      = f.label :how_did_you_learn_about, "How did they learn about this tool?"
      = f.text_area :how_did_you_learn_about, rows: 2, class: 'new_user_text_fields'

  .indent
    - if policy(current_user).set_roles?
      .field
        %h2
          Roles
        #role-select
          = render "role_select.html"

  .indent
    - if policy(current_user).approve?
      %h2 Approval
      .indent
        .field
          = f.label :approved, "Approved:"
          = f.check_box :approved

    %h2 Diagram Sharing:
    .indent
      .field
        - source_for_diagrams = (current_user.has_role?('institution-admin') || current_user.super_admin ? current_user.institution : current_user)
        = select_tag :user_diagrams,
            options_for_select(source_for_diagrams.diagrams.map{|d| ["#{d.name} -- #{d.category}", d.id  ]},
                                :selected => @user.diagrams.map(&:id)),
            {:multiple => true}

      %p
        %b This user will automatically be given access to the following diagrams because of the permissions set on each diagram:
        #shared_diagrams_table.indent
          %table.datatable.responsive.no-wrap{:data => {:paging => 'false'}}
            %thead
              %tr
                %th Name
                %th Category
                %th Creator
                %th Edit
              %tbody
                - ( @user.institution.diagrams.where(:share_with_all => true)| Diagram.where(:share_with_all_institutions => true) ).each do |diagram|
                  %tr
                    %td= diagram.name
                    %td= diagram.category
                    %td= diagram.creator.institution == current_user.institution ? diagram.creator.name : diagram.institution.name
                    - if policy(diagram).edit?
                      %td= link_to 'Edit', edit_diagram_path(diagram)



  .actions
    = f.submit 'Save', :id => "user_submit"


:javascript
  $("#user_diagrams").select2({
      width:'300px',
      allowClear:true
  });

app/views/users/_role_select.html.haml
%ul
  %li
    %p Users with no assigned roles can only view diagrams.  They can only view diagrams shared with them and they can not download the underlying data.
  %li
    %p Institution admins (assigned the role 'institution-admin') can see all diagrams and do everything.
  %li
    %p Institution admins and users with the 'user-approve' role will be emailed by the system when a new user registers.
  %li
    %p Users who aren't institution admins can only grant roles to users that they also possess.
  %li
    %p Some roles functionally depend on other roles.  For instance, it would be pretty hard to update a user if you can't view the user list.  When a role with a dependency is added the application will automatically add the required roles and notify the user.

.indent
  %table
    %thead
      %tr
        %th
        %th Role
        %th Description
        %th Required by
    %tbody
      %tr
        %td= check_box_tag 'institution-admin', 1,  false, {:class => 'role-select'}
        %td.role-name  institution-admin
        %td This role is equivalent to being granted all roles.  In addition a institution-admin can view, edit, and delete all diagrams and data created by all users in the institution regardless of if they were shared with her or him.
        %td None
      %tr
        %td= check_box_tag 'user-view', 1,  false, {:class => 'role-select'}
        %td.role-name  user-view
        %td This role grants the user access to the user list and the user show page with more information about the user.
        %td user-update, user-delete
      %tr
        %td= check_box_tag 'user-update', 1,  false, {:class => 'role-select'}
        %td.role-name  user-update
        %td This role grants the user access to the user edit page.
        %td user-approve, user-set-roles
      %tr
        %td= check_box_tag 'user-set-roles', 1,  false, {:class => 'role-select'}
        %td.role-name  user-set-roles
        %td This role allows a user to edit the roles of other users.  A user can only grant roles that he or she also possesses.
        %td None
      %tr
        %td= check_box_tag 'user-approve', 1,  false, {:class => 'role-select'}
        %td.role-name  user-approve
        %td This role allows a user to approve new users for your institution.  Users with this role will automatically be sent notification emails when a new user signs up.
        %td None
      %tr
        %td= check_box_tag 'user-destroy', 1,  false, {:class => 'role-select'}
        %td.role-name  user-destroy
        %td This role allows a user to delete other users.
        %td None
      %tr
        %td= check_box_tag 'diagram-create', 1,  false, {:class => 'role-select'}
        %td.role-name  diagram-create
        %td This role allows a user to create diagrams. A diagram's creator can always edit the diagram, download its data files, and view it.  Users can not delete diagrams unless they have the diagram-destroy role.
        %td diagram-update, diagram-destroy
      %tr
        %td= check_box_tag 'diagram-update', 1,  false, {:class => 'role-select'}
        %td.role-name  diagram-update
        %td This role allows a user to edit their own diagrams.  This includes changing a diagram's name, description, replacing its data files, and sharing the diagram with other users.
        %td None
      %tr
        %td= check_box_tag 'diagram-destroy', 1,  false, {:class => 'role-select'}
        %td.role-name  diagram-destroy
        %td This role allows a user to delete the diagrams they have created.
        %td None
      %tr
        %td= check_box_tag 'diagram-download', 1,  false, {:class => 'role-select'}
        %td.role-name  diagram-download
        %td This role allows a user to download diagrams that have been shared with them and that have been marked as downloadable by their creator.  Users can always download the diagrams they create.
        %td None
  #role-messages
  = button_tag "Remove All Roles", :type => "button", :id => "clear_roles"
  = hidden_field nil, :roles, :value => @user.roles.map{|r| r.name}.join(",")

  %p{:style => "color:red;"}  If these roles do not meet all the requirements for your university, please contact us so we can improve them.

:javascript
  var role_dependencies = #{@user.role_dependencies.to_json.html_safe}
  var dependent_roles = #{@user.dependent_roles.to_json.html_safe}
  var current_roles = #{@user.roles.map{|r| r.name}.to_json.html_safe}

  current_roles.forEach(function(role){
    $("#"+role).attr("checked", true);
    $("#"+role).parent().siblings(".role-name").addClass("role-selected");
  });

  $('.role-select').on("change", function(e) {
    var idSelector = function() { return this.id; };
    var vals = $(".role-select:checked").map(idSelector).get();
    var messages = [];
    var changed_role = $(this).attr("id");

    vals.forEach(function(role){
      var role_to_add = role_dependencies[role];
      var dependent_role = role;

      if (role_to_add != changed_role) {
        while (role_to_add != undefined && vals.indexOf(role_to_add) == -1){
          messages.push("The role "+dependent_role+" depends on the role "+role_to_add+". "+role_to_add+" has been automatically added.");
          vals.push(role_to_add);
          dependent_role = role_to_add;
          role_to_add = role_dependencies[role_to_add];
        }
      }
    });

    if ($(this).is(':not(:checked)') && dependent_roles[changed_role] != undefined){
      dependent_roles[changed_role].forEach(function(role){
        var index = vals.indexOf(role);
        if (index > -1) {
           vals.splice(index, 1);
           messages.push("The role "+role+" depends on the role "+changed_role+". "+role+" has been automatically removed.");
        }
      });
    }

    $(".role-name").removeClass("role-selected");
    $(".role-select").prop("checked",false);
    vals.forEach(function(role){
      var e = $("#"+role)
      e.prop("checked",true);
      e.parent().siblings(".role-name").addClass("role-selected");
    });

    $("#roles").val(vals.join(","));

    $("#role-messages").html("");
    messages.forEach(function(m){
      $("#role-messages").append("<p>"+m+"</p>");
    });

    return true;
  });

  $("#clear_roles").click(function(){
    $(".role-name").removeClass("role-selected");
    $(".role-select").prop("checked",false);
    $("#roles").val('');
  });

  $(document).ready(function() {
    $(window).keydown(function(event){
      if(event.keyCode == 13) {
        event.preventDefault();
        return false;
      }
    });
  });

app/views/users/edit.html.haml
#header
  %p
    You are:
    %a{ href: user_path(current_user) }
      = current_user.name
  .slicknav-container
    .slicknav
    %ul#menu{ style: "display:none;" }
      %li= link_to 'Home', root_path
      - if policy(User).index?
        %li= link_to 'Users', users_path
      - if policy(Diagram).create?
        %li
          Diagrams
          %ul
            %li= link_to 'List', diagrams_path
            %li= link_to 'Create', new_diagram_path
      - else
        %li= link_to 'Diagrams', diagrams_path
      - if current_user.super_admin
        %li= link_to 'Institutions', institutions_path
      %li= link_to 'Sign out', destroy_user_session_path, method: :delete

  %h1#site_title
    = link_to "Ribbon Tool", root_path

%h2
  Editing User
  = @user.name

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
#header
  %p
    You are:
    %a{ href: user_path(current_user) }
      = current_user.name
  .slicknav-container
    .slicknav
    %ul#menu{ style: "display:none;" }
      %li= link_to 'Home', root_path
      - if policy(User).index?
        %li= link_to 'Users', users_path
      - if policy(Diagram).create?
        %li
          Diagrams
          %ul
            %li= link_to 'List', diagrams_path
            %li= link_to 'Create', new_diagram_path
      - else
        %li= link_to 'Diagrams', diagrams_path
      - if current_user.super_admin
        %li= link_to 'Institutions', institutions_path

      - if current_user.has_role?('institution-admin') || current_user.super_admin
        %li= link_to 'Download User Logs (CSV)', export_user_logs_path, { target: "_blank" }
        %li= link_to 'Download User Info (CSV)', export_all_users_path, class: 'btn btn-primary', target: '_blank'

      %li= link_to 'Sign out', destroy_user_session_path, method: :delete

  %h1#site_title
    = link_to "Ribbon Tool", root_path

%h2 Listing users
%p Users with <strong>bold</strong> names are admins.
%p Users with <strong style="color:red;">red</strong> names are waiting for approval from an admin.

Show:
= link_to "All Users", :action => "index"
- if policy(current_user).approve?
  |
  = link_to "Users awaiting approval", :action => "index", :approved => "false"
  |
  = link_to "Export List of Users Awaiting Approval", :action => "export_users_awaiting_approval"

%table.datatable.responsive.no-wrap
  %thead
    %tr
      %th Name
      %th Email
      %th{ style: "width: 10%; white-space: normal;" } Department
      %th Roles
      - if current_user.has_role?('institution-admin') || current_user.super_admin?
        %th Last Login
      %th
      - if policy(current_user).edit?
        %th
      - if policy(current_user).destroy?
        %th
  %tbody
    - @users.each do |user|
      %tr
        %td
          - if user.approved == false
            #not-approved-name= user.name
          - elsif user.has_role? 'institution-admin'
            #admin-name= user.name
          - else
            = user.name
        %td= user.email
        %td{ style: "white-space: normal;" }= user.department.present? ? user.department : 'N/A'
        %td
          - if user.role_list.empty?
            No Roles Assigned
          - else
            - user.role_list.each do |role|
              = role
              %br
        - if current_user.has_role?('institution-admin') || current_user.super_admin?
          %td= user.last_sign_in_at ? user.last_sign_in_at.in_time_zone("Eastern Time (US & Canada)").strftime("%Y-%m-%d %H:%M") : 'Never'
        %td= link_to 'Show', user
        - if policy(current_user).edit?
          %td= link_to 'Edit', edit_user_path(user)
        - if policy(current_user).destroy?
          %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/users/new.html.haml
%h2 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
#header
  %p
    You are:
    %a{ href: user_path(current_user) }
      = current_user.name
  .slicknav-container
    .slicknav
    %ul#menu{ style: "display:none;" }
      %li= link_to 'Home', root_path
      - if policy(User).index?
        %li= link_to 'Users', users_path
      - if policy(Diagram).create?
        %li
          Diagrams
          %ul
            %li= link_to 'List', diagrams_path
            %li= link_to 'Create', new_diagram_path
      - else
        %li= link_to 'Diagrams', diagrams_path
      - if current_user.super_admin?
        %li= link_to 'Institutions', institutions_path
      %li= link_to 'Sign out', destroy_user_session_path, method: :delete

  %h1#site_title
    = link_to "Ribbon Tool", root_path

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Umd Directory Username:
  = @user.username
%p
  %b UMD Directory ID Number:
  = @user.uid_number
%p
  %b Title:
  = @user.title
%p
  %b Department:
  = @user.department

- if policy(current_user).set_roles?
  %p
    %b Roles:
  %ul
    - @user.roles.each do |role|
      %li= role

%p
  %b Why did they want the access?
  = @user.why_give_access
%p
  %b How did they learn about this tool:
  = @user.how_did_you_learn_about

- if current_user.has_role?('institution-admin') || current_user.super_admin?
  %p
    %b Last sign in at:
    %b= @user.last_sign_in_at ? @user.last_sign_in_at.in_time_zone("Eastern Time (US & Canada)").strftime("%Y-%m-%d %H:%M") : 'Never'

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path